[package]
name = "encbckup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
brotli = "3.3.4"
cryptostream = "0.3.2"
openssl = "0.10.45"
rand = "0.8"
